// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtU9v_4eSziogHTm7eD-TWsLgHoVOE90o',
    appId: '1:434644951500:web:4f5d4ca98284d4a6297d69',
    messagingSenderId: '434644951500',
    projectId: 'safequest-4358c',
    authDomain: 'safequest-4358c.firebaseapp.com',
    storageBucket: 'safequest-4358c.firebasestorage.app',
    measurementId: 'G-K9KPHD51LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAopVogYbD0oSz6Hobd5RA2KNzfRsHdeO8',
    appId: '1:434644951500:android:8f1a9982db198253297d69',
    messagingSenderId: '434644951500',
    projectId: 'safequest-4358c',
    storageBucket: 'safequest-4358c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9r3j1mxM8KJqe_xdC_Q_wA8OIc7VWlZ4',
    appId: '1:434644951500:ios:ebf42a0cb5f062f2297d69',
    messagingSenderId: '434644951500',
    projectId: 'safequest-4358c',
    storageBucket: 'safequest-4358c.firebasestorage.app',
    androidClientId: '434644951500-6qkflrdh8hci5qslo430psc0ggrma1sv.apps.googleusercontent.com',
    iosClientId: '434644951500-j24ctbc9ah8iuc4g1st637p1bpue28a6.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoSafequest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9r3j1mxM8KJqe_xdC_Q_wA8OIc7VWlZ4',
    appId: '1:434644951500:ios:ebf42a0cb5f062f2297d69',
    messagingSenderId: '434644951500',
    projectId: 'safequest-4358c',
    storageBucket: 'safequest-4358c.firebasestorage.app',
    androidClientId: '434644951500-6qkflrdh8hci5qslo430psc0ggrma1sv.apps.googleusercontent.com',
    iosClientId: '434644951500-j24ctbc9ah8iuc4g1st637p1bpue28a6.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoSafequest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtU9v_4eSziogHTm7eD-TWsLgHoVOE90o',
    appId: '1:434644951500:web:fe542cf93650c3dc297d69',
    messagingSenderId: '434644951500',
    projectId: 'safequest-4358c',
    authDomain: 'safequest-4358c.firebaseapp.com',
    storageBucket: 'safequest-4358c.firebasestorage.app',
    measurementId: 'G-0NRYC9BVEZ',
  );
}
